<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Room', 'doctrine');

/**
 * BaseRoom
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $hotel_id
 * @property integer $room_category_id
 * @property string $number
 * @property RoomCategory $RoomCategory
 * @property Doctrine_Collection $RoomOccupancyRecords
 * 
 * @method integer             getHotelId()              Returns the current record's "hotel_id" value
 * @method integer             getRoomCategoryId()       Returns the current record's "room_category_id" value
 * @method string              getNumber()               Returns the current record's "number" value
 * @method RoomCategory        getRoomCategory()         Returns the current record's "RoomCategory" value
 * @method Doctrine_Collection getRoomOccupancyRecords() Returns the current record's "RoomOccupancyRecords" collection
 * @method Room                setHotelId()              Sets the current record's "hotel_id" value
 * @method Room                setRoomCategoryId()       Sets the current record's "room_category_id" value
 * @method Room                setNumber()               Sets the current record's "number" value
 * @method Room                setRoomCategory()         Sets the current record's "RoomCategory" value
 * @method Room                setRoomOccupancyRecords() Sets the current record's "RoomOccupancyRecords" collection
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRoom extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('room');
        $this->hasColumn('hotel_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('room_category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('number', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RoomCategory', array(
             'local' => 'room_category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('RoomOccupancy as RoomOccupancyRecords', array(
             'local' => 'id',
             'foreign' => 'room_id'));
    }
}