<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Package', 'doctrine');

/**
 * BasePackage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $hotel_id
 * @property string $name
 * @property string $description
 * @property Hotel $Hotel
 * @property Doctrine_Collection $PackageItems
 * @property Doctrine_Collection $PackageItem2Package
 * 
 * @method integer             getHotelId()             Returns the current record's "hotel_id" value
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getDescription()         Returns the current record's "description" value
 * @method Hotel               getHotel()               Returns the current record's "Hotel" value
 * @method Doctrine_Collection getPackageItems()        Returns the current record's "PackageItems" collection
 * @method Doctrine_Collection getPackageItem2Package() Returns the current record's "PackageItem2Package" collection
 * @method Package             setHotelId()             Sets the current record's "hotel_id" value
 * @method Package             setName()                Sets the current record's "name" value
 * @method Package             setDescription()         Sets the current record's "description" value
 * @method Package             setHotel()               Sets the current record's "Hotel" value
 * @method Package             setPackageItems()        Sets the current record's "PackageItems" collection
 * @method Package             setPackageItem2Package() Sets the current record's "PackageItem2Package" collection
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePackage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('package');
        $this->hasColumn('hotel_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Hotel', array(
             'local' => 'hotel_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('PackageItem as PackageItems', array(
             'refClass' => 'PackageItem2Package',
             'local' => 'package_id',
             'foreign' => 'package_item_id'));

        $this->hasMany('PackageItem2Package', array(
             'local' => 'id',
             'foreign' => 'package_id'));
    }
}