<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RoomOccupancy', 'doctrine');

/**
 * BaseRoomOccupancy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $hotel_id
 * @property integer $room_occupancy_entity_id
 * @property integer $room_id
 * @property integer $booking_id
 * @property string $info
 * @property date $date
 * @property boolean $is_arrival
 * @property boolean $is_departure
 * @property boolean $is_occupied
 * @property boolean $is_closed
 * @property Hotel $Hotel
 * @property Room $Room
 * @property RoomOccupancyEntity $RoomOccupancyEntity
 * 
 * @method integer             getHotelId()                  Returns the current record's "hotel_id" value
 * @method integer             getRoomOccupancyEntityId()    Returns the current record's "room_occupancy_entity_id" value
 * @method integer             getRoomId()                   Returns the current record's "room_id" value
 * @method integer             getBookingId()                Returns the current record's "booking_id" value
 * @method string              getInfo()                     Returns the current record's "info" value
 * @method date                getDate()                     Returns the current record's "date" value
 * @method boolean             getIsArrival()                Returns the current record's "is_arrival" value
 * @method boolean             getIsDeparture()              Returns the current record's "is_departure" value
 * @method boolean             getIsOccupied()               Returns the current record's "is_occupied" value
 * @method boolean             getIsClosed()                 Returns the current record's "is_closed" value
 * @method Hotel               getHotel()                    Returns the current record's "Hotel" value
 * @method Room                getRoom()                     Returns the current record's "Room" value
 * @method RoomOccupancyEntity getRoomOccupancyEntity()      Returns the current record's "RoomOccupancyEntity" value
 * @method RoomOccupancy       setHotelId()                  Sets the current record's "hotel_id" value
 * @method RoomOccupancy       setRoomOccupancyEntityId()    Sets the current record's "room_occupancy_entity_id" value
 * @method RoomOccupancy       setRoomId()                   Sets the current record's "room_id" value
 * @method RoomOccupancy       setBookingId()                Sets the current record's "booking_id" value
 * @method RoomOccupancy       setInfo()                     Sets the current record's "info" value
 * @method RoomOccupancy       setDate()                     Sets the current record's "date" value
 * @method RoomOccupancy       setIsArrival()                Sets the current record's "is_arrival" value
 * @method RoomOccupancy       setIsDeparture()              Sets the current record's "is_departure" value
 * @method RoomOccupancy       setIsOccupied()               Sets the current record's "is_occupied" value
 * @method RoomOccupancy       setIsClosed()                 Sets the current record's "is_closed" value
 * @method RoomOccupancy       setHotel()                    Sets the current record's "Hotel" value
 * @method RoomOccupancy       setRoom()                     Sets the current record's "Room" value
 * @method RoomOccupancy       setRoomOccupancyEntity()      Sets the current record's "RoomOccupancyEntity" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRoomOccupancy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('room_occupancy');
        $this->hasColumn('hotel_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('room_occupancy_entity_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('room_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('booking_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('info', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('is_arrival', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('is_departure', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('is_occupied', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('is_closed', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Hotel', array(
             'local' => 'hotel_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Room', array(
             'local' => 'room_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('RoomOccupancyEntity', array(
             'local' => 'room_occupancy_entity_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}