<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RoomGallery', 'doctrine');

/**
 * BaseRoomGallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $room_category_id
 * @property string $image
 * @property RoomCategory $RoomCategory
 * 
 * @method integer      getRoomCategoryId()   Returns the current record's "room_category_id" value
 * @method string       getImage()            Returns the current record's "image" value
 * @method RoomCategory getRoomCategory()     Returns the current record's "RoomCategory" value
 * @method RoomGallery  setRoomCategoryId()   Sets the current record's "room_category_id" value
 * @method RoomGallery  setImage()            Sets the current record's "image" value
 * @method RoomGallery  setRoomCategory()     Sets the current record's "RoomCategory" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRoomGallery extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('room_gallery');
        $this->hasColumn('room_category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RoomCategory', array(
             'local' => 'room_category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $imagebuilder0 = new Doctrine_Template_ImageBuilder(array(
             ));
        $this->actAs($imagebuilder0);
    }
}