<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PriceItem', 'doctrine');

/**
 * BasePriceItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $price_item_type
 * @property integer $hotel_id
 * @property date $date
 * @property float $price
 * @property integer $room_category_id
 * @property integer $package_item_id
 * @property Hotel $Hotel
 * @property RoomCategory $RoomCategory
 * 
 * @method integer      getPriceItemType()    Returns the current record's "price_item_type" value
 * @method integer      getHotelId()          Returns the current record's "hotel_id" value
 * @method date         getDate()             Returns the current record's "date" value
 * @method float        getPrice()            Returns the current record's "price" value
 * @method integer      getRoomCategoryId()   Returns the current record's "room_category_id" value
 * @method integer      getPackageItemId()    Returns the current record's "package_item_id" value
 * @method Hotel        getHotel()            Returns the current record's "Hotel" value
 * @method RoomCategory getRoomCategory()     Returns the current record's "RoomCategory" value
 * @method PriceItem    setPriceItemType()    Sets the current record's "price_item_type" value
 * @method PriceItem    setHotelId()          Sets the current record's "hotel_id" value
 * @method PriceItem    setDate()             Sets the current record's "date" value
 * @method PriceItem    setPrice()            Sets the current record's "price" value
 * @method PriceItem    setRoomCategoryId()   Sets the current record's "room_category_id" value
 * @method PriceItem    setPackageItemId()    Sets the current record's "package_item_id" value
 * @method PriceItem    setHotel()            Sets the current record's "Hotel" value
 * @method PriceItem    setRoomCategory()     Sets the current record's "RoomCategory" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePriceItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('price_item');
        $this->hasColumn('price_item_type', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('hotel_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('price', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('room_category_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('package_item_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Hotel', array(
             'local' => 'hotel_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('RoomCategory', array(
             'local' => 'room_category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}