<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PackageItem', 'doctrine');

/**
 * BasePackageItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $hotel_id
 * @property string $name
 * @property boolean $per_adult
 * @property boolean $per_child
 * @property Hotel $Hotel
 * @property Doctrine_Collection $Packages
 * @property Doctrine_Collection $PackageItem2Package
 * @property Doctrine_Collection $PackageItem2ChildCategory
 * 
 * @method integer             getHotelId()                   Returns the current record's "hotel_id" value
 * @method string              getName()                      Returns the current record's "name" value
 * @method boolean             getPerAdult()                  Returns the current record's "per_adult" value
 * @method boolean             getPerChild()                  Returns the current record's "per_child" value
 * @method Hotel               getHotel()                     Returns the current record's "Hotel" value
 * @method Doctrine_Collection getPackages()                  Returns the current record's "Packages" collection
 * @method Doctrine_Collection getPackageItem2Package()       Returns the current record's "PackageItem2Package" collection
 * @method Doctrine_Collection getPackageItem2ChildCategory() Returns the current record's "PackageItem2ChildCategory" collection
 * @method PackageItem         setHotelId()                   Sets the current record's "hotel_id" value
 * @method PackageItem         setName()                      Sets the current record's "name" value
 * @method PackageItem         setPerAdult()                  Sets the current record's "per_adult" value
 * @method PackageItem         setPerChild()                  Sets the current record's "per_child" value
 * @method PackageItem         setHotel()                     Sets the current record's "Hotel" value
 * @method PackageItem         setPackages()                  Sets the current record's "Packages" collection
 * @method PackageItem         setPackageItem2Package()       Sets the current record's "PackageItem2Package" collection
 * @method PackageItem         setPackageItem2ChildCategory() Sets the current record's "PackageItem2ChildCategory" collection
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePackageItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('package_item');
        $this->hasColumn('hotel_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('per_adult', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('per_child', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Hotel', array(
             'local' => 'hotel_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Package as Packages', array(
             'refClass' => 'PackageItem2Package',
             'local' => 'package_item_id',
             'foreign' => 'package_id'));

        $this->hasMany('PackageItem2Package', array(
             'local' => 'id',
             'foreign' => 'package_item_id'));

        $this->hasMany('PackageItem2ChildCategory', array(
             'local' => 'id',
             'foreign' => 'package_item_id'));
    }
}