<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HotelConfig', 'doctrine');

/**
 * BaseHotelConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $hotel_id
 * @property string $keyname
 * @property integer $section
 * @property string $datatype
 * @property string $label
 * @property string $value
 * @property boolean $is_hidden
 * @property Hotel $Hotel
 * 
 * @method integer     getHotelId()   Returns the current record's "hotel_id" value
 * @method string      getKeyname()   Returns the current record's "keyname" value
 * @method integer     getSection()   Returns the current record's "section" value
 * @method string      getDatatype()  Returns the current record's "datatype" value
 * @method string      getLabel()     Returns the current record's "label" value
 * @method string      getValue()     Returns the current record's "value" value
 * @method boolean     getIsHidden()  Returns the current record's "is_hidden" value
 * @method Hotel       getHotel()     Returns the current record's "Hotel" value
 * @method HotelConfig setHotelId()   Sets the current record's "hotel_id" value
 * @method HotelConfig setKeyname()   Sets the current record's "keyname" value
 * @method HotelConfig setSection()   Sets the current record's "section" value
 * @method HotelConfig setDatatype()  Sets the current record's "datatype" value
 * @method HotelConfig setLabel()     Sets the current record's "label" value
 * @method HotelConfig setValue()     Sets the current record's "value" value
 * @method HotelConfig setIsHidden()  Sets the current record's "is_hidden" value
 * @method HotelConfig setHotel()     Sets the current record's "Hotel" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHotelConfig extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hotel_config');
        $this->hasColumn('hotel_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('keyname', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('section', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 1,
             'length' => 2,
             ));
        $this->hasColumn('datatype', 'string', 32, array(
             'type' => 'string',
             'default' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('label', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('value', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_hidden', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Hotel', array(
             'local' => 'hotel_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}