<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Hotel', 'doctrine');

/**
 * BaseHotel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $admin_id
 * @property string $name
 * @property string $apihash
 * @property string $admin_lang
 * @property string $booking_langs
 * @property sfGuardUser $Admin
 * @property Doctrine_Collection $ConfigRecords
 * @property Doctrine_Collection $Rooms
 * @property Doctrine_Collection $RoomOccupancyRecords
 * @property Doctrine_Collection $RoomOccupancyEntities
 * @property Doctrine_Collection $PriceItems
 * @property Doctrine_Collection $Packages
 * @property Doctrine_Collection $PackageItems
 * @property Doctrine_Collection $Bookings
 * @property Doctrine_Collection $BookingRooms
 * @property Doctrine_Collection $BookingPackages
 * 
 * @method integer             getAdminId()               Returns the current record's "admin_id" value
 * @method string              getName()                  Returns the current record's "name" value
 * @method string              getApihash()               Returns the current record's "apihash" value
 * @method string              getAdminLang()             Returns the current record's "admin_lang" value
 * @method string              getBookingLangs()          Returns the current record's "booking_langs" value
 * @method sfGuardUser         getAdmin()                 Returns the current record's "Admin" value
 * @method Doctrine_Collection getConfigRecords()         Returns the current record's "ConfigRecords" collection
 * @method Doctrine_Collection getRooms()                 Returns the current record's "Rooms" collection
 * @method Doctrine_Collection getRoomOccupancyRecords()  Returns the current record's "RoomOccupancyRecords" collection
 * @method Doctrine_Collection getRoomOccupancyEntities() Returns the current record's "RoomOccupancyEntities" collection
 * @method Doctrine_Collection getPriceItems()            Returns the current record's "PriceItems" collection
 * @method Doctrine_Collection getPackages()              Returns the current record's "Packages" collection
 * @method Doctrine_Collection getPackageItems()          Returns the current record's "PackageItems" collection
 * @method Doctrine_Collection getBookings()              Returns the current record's "Bookings" collection
 * @method Doctrine_Collection getBookingRooms()          Returns the current record's "BookingRooms" collection
 * @method Doctrine_Collection getBookingPackages()       Returns the current record's "BookingPackages" collection
 * @method Hotel               setAdminId()               Sets the current record's "admin_id" value
 * @method Hotel               setName()                  Sets the current record's "name" value
 * @method Hotel               setApihash()               Sets the current record's "apihash" value
 * @method Hotel               setAdminLang()             Sets the current record's "admin_lang" value
 * @method Hotel               setBookingLangs()          Sets the current record's "booking_langs" value
 * @method Hotel               setAdmin()                 Sets the current record's "Admin" value
 * @method Hotel               setConfigRecords()         Sets the current record's "ConfigRecords" collection
 * @method Hotel               setRooms()                 Sets the current record's "Rooms" collection
 * @method Hotel               setRoomOccupancyRecords()  Sets the current record's "RoomOccupancyRecords" collection
 * @method Hotel               setRoomOccupancyEntities() Sets the current record's "RoomOccupancyEntities" collection
 * @method Hotel               setPriceItems()            Sets the current record's "PriceItems" collection
 * @method Hotel               setPackages()              Sets the current record's "Packages" collection
 * @method Hotel               setPackageItems()          Sets the current record's "PackageItems" collection
 * @method Hotel               setBookings()              Sets the current record's "Bookings" collection
 * @method Hotel               setBookingRooms()          Sets the current record's "BookingRooms" collection
 * @method Hotel               setBookingPackages()       Sets the current record's "BookingPackages" collection
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHotel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hotel');
        $this->hasColumn('admin_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('apihash', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));
        $this->hasColumn('admin_lang', 'string', 10, array(
             'type' => 'string',
             'default' => 'en',
             'length' => 10,
             ));
        $this->hasColumn('booking_langs', 'string', 255, array(
             'type' => 'string',
             'default' => 'en',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Admin', array(
             'local' => 'admin_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('HotelConfig as ConfigRecords', array(
             'local' => 'id',
             'foreign' => 'hotel_id'));

        $this->hasMany('RoomCategory as Rooms', array(
             'local' => 'id',
             'foreign' => 'hotel_id'));

        $this->hasMany('RoomOccupancy as RoomOccupancyRecords', array(
             'local' => 'id',
             'foreign' => 'hotel_id'));

        $this->hasMany('RoomOccupancyEntity as RoomOccupancyEntities', array(
             'local' => 'id',
             'foreign' => 'hotel_id'));

        $this->hasMany('PriceItem as PriceItems', array(
             'local' => 'id',
             'foreign' => 'hotel_id'));

        $this->hasMany('Package as Packages', array(
             'local' => 'id',
             'foreign' => 'hotel_id'));

        $this->hasMany('PackageItem as PackageItems', array(
             'local' => 'id',
             'foreign' => 'hotel_id'));

        $this->hasMany('Booking as Bookings', array(
             'local' => 'id',
             'foreign' => 'hotel_id'));

        $this->hasMany('BookingRoom as BookingRooms', array(
             'local' => 'id',
             'foreign' => 'hotel_id'));

        $this->hasMany('BookingPackage as BookingPackages', array(
             'local' => 'id',
             'foreign' => 'hotel_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             'builder' => 'ProjectHelper::slug_builder',
             ));
        $this->actAs($sluggable0);
    }
}