<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PackageItem2Package', 'doctrine');

/**
 * BasePackageItem2Package
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $package_item_id
 * @property integer $package_id
 * @property PackageItem $PackageItem
 * @property Package $Package
 * 
 * @method integer             getPackageItemId()   Returns the current record's "package_item_id" value
 * @method integer             getPackageId()       Returns the current record's "package_id" value
 * @method PackageItem         getPackageItem()     Returns the current record's "PackageItem" value
 * @method Package             getPackage()         Returns the current record's "Package" value
 * @method PackageItem2Package setPackageItemId()   Sets the current record's "package_item_id" value
 * @method PackageItem2Package setPackageId()       Sets the current record's "package_id" value
 * @method PackageItem2Package setPackageItem()     Sets the current record's "PackageItem" value
 * @method PackageItem2Package setPackage()         Sets the current record's "Package" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePackageItem2Package extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('package_item2_package');
        $this->hasColumn('package_item_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('package_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PackageItem', array(
             'local' => 'package_item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Package', array(
             'local' => 'package_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}