<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Booking', 'doctrine');

/**
 * BaseBooking
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $hotel_id
 * @property date $date_arrival
 * @property integer $date_departure
 * @property integer $adults
 * @property integer $children
 * @property integer $nights
 * @property string $guest_name
 * @property string $guest_email
 * @property string $guest_telephone
 * @property string $guest_wish
 * @property float $price
 * @property Hotel $Hotel
 * @property Doctrine_Collection $RoomOccupancyRecords
 * @property Doctrine_Collection $RoomOccupancyEntities
 * @property Doctrine_Collection $BookingRooms
 * @property Doctrine_Collection $BookingPackages
 * 
 * @method integer             getHotelId()               Returns the current record's "hotel_id" value
 * @method date                getDateArrival()           Returns the current record's "date_arrival" value
 * @method integer             getDateDeparture()         Returns the current record's "date_departure" value
 * @method integer             getAdults()                Returns the current record's "adults" value
 * @method integer             getChildren()              Returns the current record's "children" value
 * @method integer             getNights()                Returns the current record's "nights" value
 * @method string              getGuestName()             Returns the current record's "guest_name" value
 * @method string              getGuestEmail()            Returns the current record's "guest_email" value
 * @method string              getGuestTelephone()        Returns the current record's "guest_telephone" value
 * @method string              getGuestWish()             Returns the current record's "guest_wish" value
 * @method float               getPrice()                 Returns the current record's "price" value
 * @method Hotel               getHotel()                 Returns the current record's "Hotel" value
 * @method Doctrine_Collection getRoomOccupancyRecords()  Returns the current record's "RoomOccupancyRecords" collection
 * @method Doctrine_Collection getRoomOccupancyEntities() Returns the current record's "RoomOccupancyEntities" collection
 * @method Doctrine_Collection getBookingRooms()          Returns the current record's "BookingRooms" collection
 * @method Doctrine_Collection getBookingPackages()       Returns the current record's "BookingPackages" collection
 * @method Booking             setHotelId()               Sets the current record's "hotel_id" value
 * @method Booking             setDateArrival()           Sets the current record's "date_arrival" value
 * @method Booking             setDateDeparture()         Sets the current record's "date_departure" value
 * @method Booking             setAdults()                Sets the current record's "adults" value
 * @method Booking             setChildren()              Sets the current record's "children" value
 * @method Booking             setNights()                Sets the current record's "nights" value
 * @method Booking             setGuestName()             Sets the current record's "guest_name" value
 * @method Booking             setGuestEmail()            Sets the current record's "guest_email" value
 * @method Booking             setGuestTelephone()        Sets the current record's "guest_telephone" value
 * @method Booking             setGuestWish()             Sets the current record's "guest_wish" value
 * @method Booking             setPrice()                 Sets the current record's "price" value
 * @method Booking             setHotel()                 Sets the current record's "Hotel" value
 * @method Booking             setRoomOccupancyRecords()  Sets the current record's "RoomOccupancyRecords" collection
 * @method Booking             setRoomOccupancyEntities() Sets the current record's "RoomOccupancyEntities" collection
 * @method Booking             setBookingRooms()          Sets the current record's "BookingRooms" collection
 * @method Booking             setBookingPackages()       Sets the current record's "BookingPackages" collection
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBooking extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('booking');
        $this->hasColumn('hotel_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('date_arrival', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('date_departure', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('adults', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('children', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 2,
             ));
        $this->hasColumn('nights', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 2,
             ));
        $this->hasColumn('guest_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('guest_email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('guest_telephone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('guest_wish', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('price', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Hotel', array(
             'local' => 'hotel_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('RoomOccupancy as RoomOccupancyRecords', array(
             'local' => 'id',
             'foreign' => 'booking_id'));

        $this->hasMany('RoomOccupancyEntity as RoomOccupancyEntities', array(
             'local' => 'id',
             'foreign' => 'booking_id'));

        $this->hasMany('BookingRoom as BookingRooms', array(
             'local' => 'id',
             'foreign' => 'booking_id'));

        $this->hasMany('BookingPackage as BookingPackages', array(
             'local' => 'id',
             'foreign' => 'booking_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}