<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ChildCategory', 'doctrine');

/**
 * BaseChildCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $hotel_id
 * @property string $name
 * @property integer $age
 * @property Hotel $Hotel
 * @property Doctrine_Collection $PackageItem2ChildCategory
 * 
 * @method integer             getHotelId()                   Returns the current record's "hotel_id" value
 * @method string              getName()                      Returns the current record's "name" value
 * @method integer             getAge()                       Returns the current record's "age" value
 * @method Hotel               getHotel()                     Returns the current record's "Hotel" value
 * @method Doctrine_Collection getPackageItem2ChildCategory() Returns the current record's "PackageItem2ChildCategory" collection
 * @method ChildCategory       setHotelId()                   Sets the current record's "hotel_id" value
 * @method ChildCategory       setName()                      Sets the current record's "name" value
 * @method ChildCategory       setAge()                       Sets the current record's "age" value
 * @method ChildCategory       setHotel()                     Sets the current record's "Hotel" value
 * @method ChildCategory       setPackageItem2ChildCategory() Sets the current record's "PackageItem2ChildCategory" collection
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChildCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('child_category');
        $this->hasColumn('hotel_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('age', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Hotel', array(
             'local' => 'hotel_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('PackageItem2ChildCategory', array(
             'local' => 'id',
             'foreign' => 'child_category_id'));
    }
}