<?php

/**
 * BaseBookingPackage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $hotel_id
 * @property integer $booking_id
 * @property integer $package_id
 * @property string $package_name
 * @property float $price
 * @property Hotel $Hotel
 * @property Booking $Booking
 * @property Package $Package
 * 
 * @method integer        getHotelId()      Returns the current record's "hotel_id" value
 * @method integer        getBookingId()    Returns the current record's "booking_id" value
 * @method integer        getPackageId()    Returns the current record's "package_id" value
 * @method string         getPackageName()  Returns the current record's "package_name" value
 * @method float          getPrice()        Returns the current record's "price" value
 * @method Hotel          getHotel()        Returns the current record's "Hotel" value
 * @method Booking        getBooking()      Returns the current record's "Booking" value
 * @method Package        getPackage()      Returns the current record's "Package" value
 * @method BookingPackage setHotelId()      Sets the current record's "hotel_id" value
 * @method BookingPackage setBookingId()    Sets the current record's "booking_id" value
 * @method BookingPackage setPackageId()    Sets the current record's "package_id" value
 * @method BookingPackage setPackageName()  Sets the current record's "package_name" value
 * @method BookingPackage setPrice()        Sets the current record's "price" value
 * @method BookingPackage setHotel()        Sets the current record's "Hotel" value
 * @method BookingPackage setBooking()      Sets the current record's "Booking" value
 * @method BookingPackage setPackage()      Sets the current record's "Package" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBookingPackage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('booking_package');
        $this->hasColumn('hotel_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('booking_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('package_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('package_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('price', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Hotel', array(
             'local' => 'hotel_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Booking', array(
             'local' => 'booking_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Package', array(
             'local' => 'package_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));
    }
}