<?php

/**
 * BookingPackageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BookingPackageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BookingPackageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BookingPackage');
    }
}