<?php

/**
 * BookingRoomTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BookingRoomTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BookingRoomTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BookingRoom');
    }
}