<?php

/**
 * BookingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BookingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BookingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Booking');
    }

    public function tmListHotel(Doctrine_Query $q){
        $a = $q->getRootAlias();
        $q->andWhere("$a.hotel_id = ?", sfContext::getInstance()->getUser()->getHotelId());
        return $q;
    }
}