<?php

/**
 * ChildCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChildCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChildCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChildCategory');
    }


    public function tmListHotel(Doctrine_Query $q) {
        $a = $q->getRootAlias();
        $q->andWhere("$a.hotel_id = ?", sfContext::getInstance()->getUser()->getHotelId());
        return $q;
    }
}