<?php

/**
 * PackageItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PackageItem extends BasePackageItem
{
    protected $_prices = array();
    public function loadPrices($date_from, $date_to){
        $q = Q::c('PriceItem', 'pi')
            ->where('pi.package_item_id = ?', $this->id)
            ->andWhere('pi.date BETWEEN ? AND ?', array($date_from, $date_to))
            ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
        ;
        $Items = $q->execute();
        foreach($Items as $Item){
            $this->_prices[$Item['date']] = $Item['price'];
        }
    }

    public function getDayPrice($date){
        return isset($this->_prices[$date]) ? $this->_prices[$date] : false;
    }
}
