<?php

/**
 * PackageItem2ChildCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PackageItem2ChildCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PackageItem2ChildCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PackageItem2ChildCategory');
    }
}