<?php

/**
 * PackageItem2PackageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PackageItem2PackageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PackageItem2PackageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PackageItem2Package');
    }
}