<?php

/**
 * PriceItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PriceItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PriceItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PriceItem');
    }
}