<?php

/**
 * Room
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Room extends BaseRoom
{

    protected $_occupancy = array();
    public function loadOccupancy($from, $to) {
        $q = Q::c('RoomOccupancy', 'o')
            ->innerJoin('o.RoomOccupancyEntity e')
            ->where('o.room_id = ?', $this->id)
            ->andWhere('o.date BETWEEN ? AND ?', array($from, $to))
            ->orderBy('o.date, o.is_departure desc')
            ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
            ;

        $occupancy = $q->execute();

        foreach($occupancy as $ro){
            if(!isset($this->_occupancy[$ro['date']])){
                $this->_occupancy[$ro['date']] = array();
            }
            $ro['cssClass'] = $this->getOccupancyCssClass($ro);
            $ro['info'] = $ro['RoomOccupancyEntity']['name'];
            $ro['info2'] = $ro['RoomOccupancyEntity']['description'];
            $this->_occupancy[$ro['date']][] = $ro;
        }
    }
    public function getOccupancy($date){
        return isset($this->_occupancy[$date]) ? $this->_occupancy[$date] : null;
    }

    public function getOccupancyCssClass($ro){
        $class = '';
        foreach(array('arrival', 'departure', 'occupied', 'closed') as $val){
            if($ro['is_' . $val]){
                $class .= 'occupancy-' . $val;
            }
        }
        $types = array('1' => 'booking', '2' => 'reservation', '3' => 'lastminute', '4' => 'offer');
        foreach($types as $i => $cls){
            if($ro['RoomOccupancyEntity']['typeid'] == $i){
                $class .= ' occupancy-' . $cls;
            }
        }
        return $class;
    }
}
