<?php

/**
 * RoomOccupancyEntityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoomOccupancyEntityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RoomOccupancyEntityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RoomOccupancyEntity');
    }
}