<?php

/**
 * RoomCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RoomCategory extends BaseRoomCategory
{
    protected $_prices = array();
    protected $_currentOccupancyDescription;
    public function loadPrices($date_from, $date_to){
        $q = Q::c('PriceItem', 'pi')
            ->where('pi.room_category_id = ?', $this->id)
            ->andWhere('pi.date BETWEEN ? AND ?', array($date_from, $date_to))
            ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
            ;
        $Items = $q->execute();
        foreach($Items as $Item){
            $this->_prices[$Item['date']] = $Item['price'];
        }
    }

    public function getDayPrice($date){
        return isset($this->_prices[$date]) ? $this->_prices[$date] : false;
    }

    public function findFreeRoom($arrivalDate, $departureDate){
        foreach($this->getRooms() as $Room){
            if($Room->isFree($arrivalDate, $departureDate)){
                return $Room;
            }else{
                $this->_currentOccupancyDescription = $Room->getCurrentOccupancyDescription();
            }
        }
        return false;
    }
    public function getCurrentOccupancyDescription(){
        return $this->_currentOccupancyDescription;
    }
}
