<?php

/**
 * RoomGalleryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoomGalleryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RoomGalleryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RoomGallery');
    }

    public function tmListHotel(Doctrine_Query $q){
        $a = $q->getRootAlias();
        $q->innerJoin("$a.RoomCategory rc");
        $q->leftJoin("rc.Translation t WITH t.lang = ?", sfContext::getInstance()->getUser()->getCulture());
        return $q;
    }
}