<?php

/**
 * RoomOccupancyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoomOccupancyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RoomOccupancyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RoomOccupancy');
    }
}