<?php

/**
 * RoomOccupancyEntity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RoomOccupancyEntity extends BaseRoomOccupancyEntity
{
    const OCC_BOOKING = 1;
    const OCC_RESERVATION = 2;
    const OCC_LASTMINUTE = 3;
    const OCC_OFFER = 4;


}
