<?php

/**
 * RoomCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoomCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RoomCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RoomCategory');
    }


    public function tmListHotel(Doctrine_Query $q) {
        $a = $q->getRootAlias();
        $q->andWhere("$a.hotel_id = ?", sfContext::getInstance()->getUser()->getHotelId());
        $q->leftJoin("$a.Translation t WITH t.lang = ?", sfContext::getInstance()->getUser()->getCulture());
        return $q;
    }
}