<?php

/**
 * Created by PhpStorm.
 * User: alexradyuk
 * Date: 6/18/18
 * Time: 14:07
 */
class RoomCategoryFormHotel extends RoomCategoryForm
{
    public function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        unset($this['hotel_id']);

        $this->embedI18n(['en', 'ru']);
    }

    public function updateObject($values = null)
    {
        $this->getObject()->hotel_id = $this->getUser()->getHotelId();
        return parent::updateObject($values); // TODO: Change the autogenerated stub
    }
}