<?php

/**
 * Hotel form.
 * sfDoctrineFormGenerator *
 * @package    cms
 * @subpackage form
 * @author     Your name here
 * @version    SVN: $Id: sfDoctrineFormTemplate.php 23810 2009-11-12 11:07:44Z Kris.Wallsmith $
 */
class HotelForm extends BaseHotelForm
{
    protected $langs_delim = ',';
    public function configure()
    {
        $this->useFields(array(
            'name',
            'slug',
            'admin_lang',
            'booking_langs'
        ));

        $this->widgetSchema['admin_lang'] = new sfWidgetFormChoice([
            'choices' => [
                'en' => 'English',
                'ru' => 'Русский'
            ]
        ]);
        $this->widgetSchema['booking_langs'] = new sfWidgetFormChoice([
            'choices' => [
                'en' => 'English',
                'ru' => 'Русский'
            ],
            'multiple' => true
        ]);
        $this->validatorSchema['booking_langs'] = new sfValidatorChoice([
            'choices' => ['en', 'ru'],
            'multiple' => true
        ]);
    }

    public function updateDefaultsFromObject()
    {
        parent::updateDefaultsFromObject(); // TODO: Change the autogenerated stub

        $booking_langs = $this->getObject()->booking_langs;
        $booking_langs = explode($this->langs_delim, $booking_langs);
        $this->setDefault('booking_langs', $booking_langs);
    }

    public function updateObject($values = null)
    {
        parent::updateObject($values); // TODO: Change the autogenerated stub
        $this->getObject()->booking_langs = join($this->langs_delim, $this->values['booking_langs']);
        return $this->getObject();
    }

    public function doSave($con = null)
    {
        $isNew = $this->isNew();

        parent::doSave($con); // TODO: Change the autogenerated stub

        if($isNew) {
            $options = require_once sfConfig::get('sf_data_dir') . '/install/options.php';

            foreach ($options as $option) {
                $hc = new HotelConfig();
                $hc->fromArray([
                    'hotel_id' => $this->getObject()->id,
                    'keyname' => $option[0],
                    'section' => $option[1],
                    'datatype' => $option[2],
                    'label' => $option[3],
                    'value' => $option[4],
                    'is_hidden' => !empty($option[5]) ? true : false
                ]);
                $hc->save();
            }
        }
    }
}
